### ISSUE TITLE
Error after Upgrading to Anki 2.1.24

### ISSUE THREAD

**Issue by hugomarins** [glutanimate/spell-checker-public#2]
#### Problem description

Since I updated to Anki 2.1.24 version, sometimes suddenly the error message below appears (indicating spell checker conflict), and then I cannot even close the error message or Anki, and need to close Anki by the Windows task manager.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    
    Anki 2.1.24 (359b9f5c) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2020-05-02 20:22:33
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Add Hyperlink ['318752047', 2020-04-03T13:06, 'None', '']
    Add Table ['1237621971', 2020-04-27T17:52, 'None', mod]
    Advanced Browser ['874215009', 2020-04-22T19:45, 'None', '']
    Advanced Copy Fields ['1898445115', 2019-09-24T08:01, 'None', '']
    Anki Simulator ['anki_simulator', 2020-03-28T16:47, 'None', '']
    Anki Zoom ['538879081', 2020-04-03T21:20, 'v1.1.3', mod]
    Answer Confirmation for 21 ['1354051622', 2019-09-24T08:34, 'None', '']
    AwesomeTTS Google Cloud Text-to-Speech unofficial ['814349176', 2020-04-14T09:51, 'None', '']
    Batch Editing ['291119185', 2019-09-24T07:39, 'None', '']
    BetterTags ['bettertags', 2020-04-28T12:40, 'None', '']
    Cloze Overlapper ['cloze_overlapper', 2019-02-01T09:37, 'None', '']
    Copy notes ['1566928056', 2020-03-11T21:56, 'None', mod]
    Create Filtered Deck from the Browser ['861263371', 2019-09-24T08:34, 'None', '']
    Customize Keyboard Shortcuts ['24411424', 2020-03-11T02:05, 'None', '']
    Deck name in title 21 ['699175524', 2019-09-24T08:37, 'None', '']
    Edit Field During Review ['1020366288', 2020-01-29T13:33, 'None', '']
    Enhance main window ['877182321', 2020-02-15T23:51, 'None', mod]
    External Note Editor for the Browser ['browser_external_note_editor', 2020-03-10T14:42, 'None', '']
    Fast Word Query Multi-threaded queries for words from local or web dictionaries ['1807206748', 2019-09-24T07:41, 'None', '']
    Highlight Search Results in the Browser ['225180905', 2019-09-24T07:45, 'None', '']
    Hitmarkers ['1776869150', 2020-03-31T19:04, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-27T23:21, 'None', '']
    Keep model of add cards ['424778276', 2020-05-02T11:05, 'None', '']
    LPCG LyricsPoetry Cloze Generator ['2084557901', 2019-09-24T07:46, 'None', '']
    Large and Colorful Buttons ['1829090218', 2019-11-16T22:31, 'None', '']
    Mini Format Pack ['295889520', 2019-09-24T07:40, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2020-03-31T17:19, 'None', '']
    More Overview Stats 21 ['738807903', 2019-09-24T08:22, 'None', '']
    Multiple Choice for Anki ['1566095810', 2020-04-10T02:50, 'None', '']
    Newline in strings in add-ons configurations ['112201952', 2020-03-19T15:41, 'None', '']
    Opening the same window multiple time ['354407385', 2020-03-09T08:57, 'None', '']
    PDF Glossary Exporter ['pdf_glossary', 2019-08-19T09:35, 'None', '']
    Pop-up Dictionary beta ['153625306', 2019-09-24T08:33, 'None', '']
    Quick Colour Changing ['2491935955', 2019-09-24T08:35, 'None', mod]
    ReMemorize Rescheduler with sibling and logging v140 ['323586997', 2020-04-17T04:07, 'None', mod]
    Search Everywhere - Ctrl+F Find ['search_everywhere', 2020-03-31T17:13, 'None', '']
    Show fields source html in editor ['1574324795', 2020-03-28T04:08, 'None', '']
    Speed Focus Mode auto-alert auto-reveal auto-fail ['1046608507', 2019-06-02T06:11, 'None', '']
    Spell Checker ['spell_checker', 0, 'None', '']
    Symbols ['1461102936', 2019-09-24T08:35, 'None', mod]
    add-on dialog searchfilter bar ['561945101', 2020-01-21T19:42, 'None', '']
    deck and card info sidebar during review ['673114053', 2020-04-16T14:50, 'None', mod]
    editor apply font color background color custom class custom style ['1899278645', 2020-01-22T11:51, 'None', '']
    export cardsnotes from browser with metadata to csv or xlsx ['1967530655', 2020-04-16T09:07, 'None', '']
    extended table editor ['805891399', 2020-04-28T05:01, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    1020366288 1046608507 112201952 1237621971 1354051622 1374772155 1461102936 153625306 1556734708 1566095810 1566928056 1574324795 1776869150 1807206748 1829090218 1898445115 1899278645 1967530655 2084557901 225180905 24411424 2491935955 291119185 295889520 318752047 323586997 354407385 424778276 538879081 561945101 673114053 699175524 738807903 805891399 814349176 861263371 874215009 877182321
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
      Advanced Review Bottom Bar   ['1136455830', 2020-05-01T11:32, 'None', mod]
    Advanced Card Styles ['1625103157', 2019-09-24T08:25, 'None', '']
    Customize Editor Stylesheet ['1215991469', 2019-09-24T09:07, 'None', '']
    Customize Sidebar ['1988760596', 2020-01-15T18:01, 'None', '']
    Editor Autocomplete ['924298715', 2020-01-18T07:02, 'None', '']
    Export cards selected in the Browser ['1983204951', 2020-02-03T13:31, 'None', '']
    Graphical form to change add-on configuration ['1014777615', 2020-03-19T07:22, 'None', '']
    Puppy Reinforcement ['puppy_reinforcement', 2020-03-02T16:22, 'None', mod]
    Show LaTeXs result in editorbrowser ['882784122', 2020-03-26T12:58, 'None', '']
    Trigger and actions change one card depending on what occurs on another card ['1981494159', 2020-03-19T21:19, 'None', mod]
    Visual Feedback for Reviews ['review_feedback', 2020-01-29T16:43, 'None', mod]


```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.24 (359b9f5c) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-05-02 20:22:33

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 43, in handler
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-58>", line 2, in _closeWindow
  File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 629, in repl
  File "aqt\browser.py", line 702, in _closeWindow
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-82>", line 2, in cleanup
  File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 632, in repl
  File "C:\Users\hugom\AppData\Roaming\Anki2\addons21\spell_checker\editor.py", line 200, in onEditorCleanup
    remHook("spellLangsUpdated", self.web.setupSpellcheck)
AttributeError: 'NoneType' object has no attribute 'setupSpellcheck'

```

**Comment by hugomarins** [comment]
Aristotelis, I think the problem was on Arthur's "Keep model of add cards"; anyway, he has already solved it and the problem is not occurring anymore. Thanks!
